# Definição do Problema
___
> **Definição**

*O naufrágio do Titantic resultou na morte de 1502 dos 2224 passageiros e tripulantes.*

*Embora houvesse algum elemento de sorte envolvido na sobrevivência, parece que alguns grupos de pessoas eram mais propensos a sobreviver do que outros.*

*Construa um modelo preditivo que responda à pergunta:*
    ***"Que tipo de pessoas têm maior probabilidade de sobreviver?".***

___
> **Dataset**

*Dois conjuntos de dados semelhantes, que incluem informações sobre passageiros como nome, idade, sexo, classe socioeconômica, etc.*

*Um conjunto de dados é intitulado "train.csv" e o outro é intitulado "test.csv".*

- *O Train.csv conterá os detalhes de um subconjunto dos passageiros a bordo (891) e, mais importante, revelará se eles sobreviveram ou não, também conhecida como "verdade do solo".*

- *O Test.csv contém informações semelhantes, mas não divulga a "verdade básica" para cada passageiro. É seu trabalho prever esses resultados.*

___
> **Link**

- [Kaggle: Titanic.](https://www.kaggle.com/c/titanic/data)

___
> **Objetivo**

*Usando os padrões encontrados nos dados train.csv,* ***preveja se os outros 418 passageiros a bordo (encontrados em test.csv) sobreviveram.***
